accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup')
]

blog/urls.py
from django.urls import path

from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView
)

urlpatterns = [
    path(
        'post/<int:pk>/delete/',
        BlogDeleteView.as_view(),
        name='post_delete'),
    path(
        'post/<int:pk>/edit/',
        BlogUpdateView.as_view(),
        name='post_edit'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('', BlogListView.as_view(), name='home')
]

django_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Post


class BlogListView(ListView):
    model = Post
    template_name = 'home.html'

class BlogDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'

class BlogCreateView(CreateView):
    model = Post
    template_name = 'post_new.html'
    fields = '__all__'

class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'post_edit.html'
    fields = ['title', 'body']

class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Blog</title>

    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>
<body>
    <header>
        <div class="nav-left">
            <h1><a href="{% url 'home' %}">Django Blog</a></h1>
        </div>
        <div class="nav-right">
            <a href="{% url 'post_new' %}">+ New Blog Post</a>
        </div>
    </header>

    {% if user.is_authenticated %}
        <p>Hi {{ user.username }}</p>
        <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
        <p>You are not logged in.</p>
        <a href="{% url 'login' %}">Log In</a>
    {% endif %}

    <div>
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% for post in post_list %}
        <div class="post-entry">
            <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.body }}</p>
        </div>
    {% endfor %}
{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Post</h1>

    <form action="" method="post"> {% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="post-entry">
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
    </div>

    <p><a href="{% url 'post_edit' post.pk %}">+ Edit Blog Post</a></p>
    <p><a href="{% url 'post_delete' post.pk %}">+ Delete Blog Post</a></p>
{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit Post</h1>

    <form action="" method="post"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update"/>
    </form>
{% endblock content %}

templates/post_new.html
{% extends 'base.html' %}

{% block content %}
    <h1>New Post</h1>

    <form action="" method="post"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save"/>
    </form>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Sign Up</h2>

    <form method="post"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
{% endblock content %}